name: Axiometa
description: "UAB Axiometa Project. Artificial Inteligence guided design."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logos/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logos/1024-mac.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/sensor_icons/
    - assets/custom_fonts/

  fonts:
    - family: Pirulen
      fonts:
        - asset: assets/custom_fonts/Pirulen.otf
